export const colors = [
    "#0099ff",
    "#ff4444",
    "#cc00cc",
    "#ff8800",
    "#00cc99",
    "#ff00ff",
    "#669900",
    "#ff6600",
    "#993399",
    "#009933",
    "#cc66ff",
    "#3399cc",
    "#993300",
    "#cc99cc",
    "#cccc00",
    "#66cc99",
    "#ff99cc",
    "#ff3366",
    "#00ccff",
    "#ffcc33",
    "#33cccc",
    "#993366",
    "#99cc00",
    "#cc3333",
    "#cc6699",
    "#ccccff",
    "#66ccff",
    "#ffcccc",
    "#66cc33",
    "#ccff66"
  ];
export const Flag =
[
'https://flagpedia.net/data/flags/h80/us.webp',
'https://flagpedia.net/data/flags/h80/mx.webp',
'https://flagpedia.net/data/flags/h80/ng.webp',
'https://flagpedia.net/data/flags/h80/ru.webp',
'https://flagpedia.net/data/flags/h80/ao.webp',
'https://flagpedia.net/data/flags/h80/in.webp',
'https://flagpedia.net/data/flags/h80/cn.webp',
'https://flagpedia.net/data/flags/h80/sa.webp',
]
  export const Countries = [
    "United States of America",
    "Mexico",
    "Nigeria",
    "Russia",
    "Lebanon",
    "Ukraine",
    "Angola",
    "South Africa",
    "Saudi Arabia",
    "Azerbaijan",
    "India",
    "Egypt",
    "Niger",
    "Colombia",
    "China",
    "Libya",
    "Indonesia",
    "Iran",
    "Iraq",
    "Brazil",
    "Mali",
    "South Sudan",
    "Venezuela",
    "United Kingdom",
    "Germany",
    "Burkina Faso",
    "Kuwait",
    "Canada",
    "Argentina",
    "Japan",
    "Estonia",
    "Austria",
    "Spain",
    "Morocco",
    "Hungary",
    "Australia",
    "Greece",
    "Qatar",
    "Oman",
    "Syria",
    "Liberia",
    "Denmark",
    "Malaysia",
    "Jordan",
    "Norway",
    "Ethiopia",
    "Ghana",
    "Kazakhstan",
    "Pakistan",
    "Gabon",
    "United Arab Emirates",
    "Algeria",
    "Turkey",
    "Cyprus",
    "Belize",
    "Poland"
  ];


  export const Style = {
    styles: {
      global: {
        '::-webkit-scrollbar': {
          width: '0.2em',
          background: 'transparent',
        },
        '::-webkit-scrollbar-thumb': {
          background: 'transparent',
        },
        '.chakra-scroll-content': {
          overflowY: 'scroll',
          scrollbarWidth: 'thin',
          scrollbarColor: 'gray',
          '&::-webkit-scrollbar': {
            width: '0.4em',
          },
          '&::-webkit-scrollbar-thumb': {
            backgroundColor: 'blue',
            borderRadius: 'md',
          },
          '&::-webkit-scrollbar-track': {
            backgroundColor: 'transparent',
          },
        },
      },
    }
  }